### ISSUE TITLE
/server should show current server

### ISSUE THREAD

**Issue by javipepe** [OvercastNetwork/Issues#1608]
<a href="http://youtu.be/79cflCbN1ks">Video</a>

**Comment by ItsMiiOlly** [comment]
I'm guessing you want to know the current server you're on?

**Comment by javipepe** [comment]
@ItsMiiOlly Correct.

**Comment by HerobrineKillerz** [comment]
Can confirm. Happened to me a few days ago.

**Comment by mrapple** [comment]
Please use better issue titles

**Comment by Electroid** [comment]
Done, at least on the 1.8 branch.

**Comment by HerobrineKillerz** [comment]
@Electroid Nope, I just tested it and it still happens on 1.8.

**Comment by matic0basle** [comment]
@HerobrineKillerz He ment he tested it on a server running complete 1.8 like Broken. So when servers switch it will be fixed.
