### ISSUE TITLE
Translated strings get double apostrophes

### ISSUE THREAD

**Issue by eudaldca** [OvercastNetwork/Issues#2243]
Strings containing an apostrophe in Crowdin get two apostrophes instead of one when shown localised.
![2015-11-24_23-20-31](https://cloud.githubusercontent.com/assets/8332105/11382425/1cc6f096-9302-11e5-87eb-e37e09d28681.png)
![2015-11-28_12 08 35](https://cloud.githubusercontent.com/assets/8332105/11451507/c7832202-95c8-11e5-8d72-64cc18582768.png)

**Comment by TiTo-418** [comment]
fixed

**Comment by eudaldca** [comment]
Not entirely @TiTo-418 
![](http://i.imgur.com/nZfLklL.png)

**Comment by eudaldca** [comment]
What Tito said was that it got fixed, but that was only for death messages, and only during some time. It now still appears. ![](http://i.imgur.com/F8RuKEl.png)
