### ISSUE TITLE
Map Authors can't see ratings after their map ended

### ISSUE THREAD

**Issue by rockymine** [OvercastNetwork/Issues#2352]
You can not see the ratings for your maps in game, even after relogging, I do have the blue star in the game but that one doesn't appear behind the maps name. I had the same issue a ton of times now, it can't be random, I can't see ratings since weeks. Other players complained about this issue too, maybe only Builders have it, not sure.

**Comment by chleongithub** [comment]
I have it too

**Comment by Tapetepato** [comment]
Can confirm it happens to me too, a map i made got played twice and i never saw any ratings, but when i checked on the website there were indeed new ones

**Comment by nigges60** [comment]
I can see ratings ingame. I think this one is fixed.

**Comment by rockymine** [comment]
This one still exists ;o Yeah. Saw ratings too... Today ;o

Am 02.10.2016 23:31 schrieb "nigges60" notifications@github.com:

**Comment by Matic0B** [comment]
Not fixed. Been experiencing this for the last couple of days. Sometimes they show, sometimes they don't. Theres also times where I don't have a blue star in chat (but do on tab) when my map is playing and times where the blue star appeares in the match after my map has ended.

**Comment by itsmartin** [comment]
Can anyone else reproduce the issue?
