### ISSUE TITLE
Nicked staff is showed in play page

### ISSUE THREAD

**Issue by Superjd10** [OvercastNetwork/Issues#826]
Hello

I think this error was already reported by roro28gutier (I told him this while following around some OCN mini-server)

The bug:
Staff using /nick is displayed in play page ( https://oc.tc/play )

This is so minor, and I used it to follow staff sometimes (never ask to "come to this server, X is hacking"), but I report it anyways.

**Comment by mrapple** [comment]
I believe this was fixed, the play page now uses sessions.

**Comment by Superjd10** [comment]
Still happens. @itsmartin nick himself and I was able to see his server in the play page, maybe because everyone can check where he is at his profile.

**Comment by Electroid** [comment]
Not anymore.
